name              'cinc-omnibus'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures cinc-omnibus'
version           '1.1.20'
chef_version      '>= 16.0'
issues_url        'https://github.com/sous-chefs/cinc-omnibus/issues'
source_url        'https://github.com/sous-chefs/cinc-omnibus'

supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'oracle'
supports 'amazon'
supports 'fedora'
supports 'debian'
supports 'ubuntu'
supports 'suse'
supports 'opensuseleap'

depends 'chef-ingredient'
