name              'cinc-omnibus'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides the cinc_omnibus_builder resource for configuring Cinc Omnibus build hosts'
version           '2.0.0'
chef_version      '>= 16.0'
issues_url        'https://github.com/sous-chefs/cinc-omnibus/issues'
source_url        'https://github.com/sous-chefs/cinc-omnibus'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'suse'
supports 'ubuntu', '>= 22.04'

depends 'chef-ingredient'
